// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tool.proto

package asthtc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VowelessJob struct {
	Phrase               string   `protobuf:"bytes,1,opt,name=Phrase,proto3" json:"Phrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VowelessJob) Reset()         { *m = VowelessJob{} }
func (m *VowelessJob) String() string { return proto.CompactTextString(m) }
func (*VowelessJob) ProtoMessage()    {}
func (*VowelessJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_34355de42c73af60, []int{0}
}

func (m *VowelessJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VowelessJob.Unmarshal(m, b)
}
func (m *VowelessJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VowelessJob.Marshal(b, m, deterministic)
}
func (m *VowelessJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VowelessJob.Merge(m, src)
}
func (m *VowelessJob) XXX_Size() int {
	return xxx_messageInfo_VowelessJob.Size(m)
}
func (m *VowelessJob) XXX_DiscardUnknown() {
	xxx_messageInfo_VowelessJob.DiscardUnknown(m)
}

var xxx_messageInfo_VowelessJob proto.InternalMessageInfo

func (m *VowelessJob) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

type AestheticJob struct {
	Phrase               string   `protobuf:"bytes,1,opt,name=Phrase,proto3" json:"Phrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AestheticJob) Reset()         { *m = AestheticJob{} }
func (m *AestheticJob) String() string { return proto.CompactTextString(m) }
func (*AestheticJob) ProtoMessage()    {}
func (*AestheticJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_34355de42c73af60, []int{1}
}

func (m *AestheticJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AestheticJob.Unmarshal(m, b)
}
func (m *AestheticJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AestheticJob.Marshal(b, m, deterministic)
}
func (m *AestheticJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AestheticJob.Merge(m, src)
}
func (m *AestheticJob) XXX_Size() int {
	return xxx_messageInfo_AestheticJob.Size(m)
}
func (m *AestheticJob) XXX_DiscardUnknown() {
	xxx_messageInfo_AestheticJob.DiscardUnknown(m)
}

var xxx_messageInfo_AestheticJob proto.InternalMessageInfo

func (m *AestheticJob) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

type DeBruijnJob struct {
	Alphabet             string   `protobuf:"bytes,1,opt,name=Alphabet,proto3" json:"Alphabet,omitempty"`
	SubSequenceSize      int32    `protobuf:"varint,2,opt,name=SubSequenceSize,proto3" json:"SubSequenceSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeBruijnJob) Reset()         { *m = DeBruijnJob{} }
func (m *DeBruijnJob) String() string { return proto.CompactTextString(m) }
func (*DeBruijnJob) ProtoMessage()    {}
func (*DeBruijnJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_34355de42c73af60, []int{2}
}

func (m *DeBruijnJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeBruijnJob.Unmarshal(m, b)
}
func (m *DeBruijnJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeBruijnJob.Marshal(b, m, deterministic)
}
func (m *DeBruijnJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeBruijnJob.Merge(m, src)
}
func (m *DeBruijnJob) XXX_Size() int {
	return xxx_messageInfo_DeBruijnJob.Size(m)
}
func (m *DeBruijnJob) XXX_DiscardUnknown() {
	xxx_messageInfo_DeBruijnJob.DiscardUnknown(m)
}

var xxx_messageInfo_DeBruijnJob proto.InternalMessageInfo

func (m *DeBruijnJob) GetAlphabet() string {
	if m != nil {
		return m.Alphabet
	}
	return ""
}

func (m *DeBruijnJob) GetSubSequenceSize() int32 {
	if m != nil {
		return m.SubSequenceSize
	}
	return 0
}

type Response struct {
	Phrase               string   `protobuf:"bytes,1,opt,name=Phrase,proto3" json:"Phrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_34355de42c73af60, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPhrase() string {
	if m != nil {
		return m.Phrase
	}
	return ""
}

func init() {
	proto.RegisterType((*VowelessJob)(nil), "asthtc.VowelessJob")
	proto.RegisterType((*AestheticJob)(nil), "asthtc.AestheticJob")
	proto.RegisterType((*DeBruijnJob)(nil), "asthtc.DeBruijnJob")
	proto.RegisterType((*Response)(nil), "asthtc.Response")
}

func init() { proto.RegisterFile("tool.proto", fileDescriptor_34355de42c73af60) }

var fileDescriptor_34355de42c73af60 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0xb0, 0x25, 0x3b, 0x2b, 0x28, 0x51, 0x64, 0xd9, 0xd3, 0x12, 0x50, 0x7a, 0xea,
	0xc1, 0xe2, 0x03, 0x54, 0x3c, 0x79, 0x92, 0x46, 0xbc, 0x37, 0x65, 0x20, 0x95, 0xd0, 0xa9, 0x9d,
	0x14, 0xc1, 0x27, 0xf2, 0x31, 0x45, 0x6d, 0x6a, 0x91, 0xba, 0xc7, 0x19, 0xbe, 0x3f, 0x3f, 0x5f,
	0x06, 0x20, 0x10, 0xf9, 0xac, 0xeb, 0x29, 0x90, 0x4a, 0x2a, 0x0e, 0x2e, 0xd4, 0xfa, 0x0a, 0x36,
	0xcf, 0xf4, 0x86, 0x1e, 0x99, 0x1f, 0xc8, 0xaa, 0x4b, 0x48, 0x1e, 0x5d, 0x5f, 0x31, 0x6e, 0xc5,
	0x5e, 0xa4, 0xeb, 0x72, 0x9c, 0xf4, 0x35, 0x9c, 0x14, 0xc8, 0xc1, 0x61, 0x68, 0xea, 0x43, 0x9c,
	0x81, 0xcd, 0x3d, 0xde, 0xf5, 0x43, 0xf3, 0xd2, 0x7e, 0x61, 0x3b, 0x90, 0x85, 0xef, 0x5c, 0x65,
	0x31, 0x8c, 0xe0, 0x34, 0xab, 0x14, 0x4e, 0xcd, 0x60, 0x0d, 0xbe, 0x0e, 0xd8, 0xd6, 0x68, 0x9a,
	0x77, 0xdc, 0x1e, 0xef, 0x45, 0xba, 0x2a, 0xff, 0xae, 0xb5, 0x06, 0x59, 0x22, 0x77, 0xd4, 0x32,
	0xfe, 0x57, 0x7c, 0xf3, 0x21, 0x60, 0xf5, 0x44, 0xe4, 0x59, 0xe5, 0x20, 0xa3, 0x91, 0x3a, 0xcf,
	0x7e, 0x34, 0xb3, 0x99, 0xe3, 0xee, 0x2c, 0x2e, 0xe3, 0xa3, 0xfa, 0x48, 0xdd, 0xc2, 0x7a, 0xf2,
	0x53, 0x17, 0x11, 0x98, 0x2b, 0x2f, 0xc6, 0x72, 0x90, 0x51, 0xf7, 0xb7, 0x6b, 0xf6, 0x01, 0x4b,
	0x21, 0x9b, 0x7c, 0x5f, 0x20, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x70, 0x37, 0x51, 0x8f,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToolsClient is the client API for Tools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToolsClient interface {
	Voweless(ctx context.Context, in *VowelessJob, opts ...grpc.CallOption) (*Response, error)
	Aesthetic(ctx context.Context, in *AestheticJob, opts ...grpc.CallOption) (*Response, error)
	DeBruijn(ctx context.Context, in *DeBruijnJob, opts ...grpc.CallOption) (*Response, error)
}

type toolsClient struct {
	cc *grpc.ClientConn
}

func NewToolsClient(cc *grpc.ClientConn) ToolsClient {
	return &toolsClient{cc}
}

func (c *toolsClient) Voweless(ctx context.Context, in *VowelessJob, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/asthtc.Tools/Voweless", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) Aesthetic(ctx context.Context, in *AestheticJob, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/asthtc.Tools/Aesthetic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolsClient) DeBruijn(ctx context.Context, in *DeBruijnJob, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/asthtc.Tools/DeBruijn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolsServer is the server API for Tools service.
type ToolsServer interface {
	Voweless(context.Context, *VowelessJob) (*Response, error)
	Aesthetic(context.Context, *AestheticJob) (*Response, error)
	DeBruijn(context.Context, *DeBruijnJob) (*Response, error)
}

func RegisterToolsServer(s *grpc.Server, srv ToolsServer) {
	s.RegisterService(&_Tools_serviceDesc, srv)
}

func _Tools_Voweless_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VowelessJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).Voweless(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asthtc.Tools/Voweless",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).Voweless(ctx, req.(*VowelessJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_Aesthetic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AestheticJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).Aesthetic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asthtc.Tools/Aesthetic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).Aesthetic(ctx, req.(*AestheticJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tools_DeBruijn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeBruijnJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolsServer).DeBruijn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asthtc.Tools/DeBruijn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolsServer).DeBruijn(ctx, req.(*DeBruijnJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tools_serviceDesc = grpc.ServiceDesc{
	ServiceName: "asthtc.Tools",
	HandlerType: (*ToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Voweless",
			Handler:    _Tools_Voweless_Handler,
		},
		{
			MethodName: "Aesthetic",
			Handler:    _Tools_Aesthetic_Handler,
		},
		{
			MethodName: "DeBruijn",
			Handler:    _Tools_DeBruijn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tool.proto",
}
